name: GroupORMA
options:
  bundleIdPrefix: com.lucaswoj
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
  schemePathPrefix: ""
  generateEmptyDirectories: true
schemes:
  GroupORMA:
    build:
      targets:
        GroupORMA: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
settings:
  base:
    SWIFT_VERSION: "5.10"
    DEVELOPMENT_TEAM: "6WCV8HHBRN"
    CODE_SIGN_STYLE: Automatic
targets:
  GroupORMA:
    type: application
    platform: iOS
    sources:
      - path: GroupORMA
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lucaswoj.grouporma
        MARKETING_VERSION: "0.1"
        CURRENT_PROJECT_VERSION: "2"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Group ORMA"
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: NO
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SDKROOT: iphoneos
