import Foundation

struct AssessmentState: Codable, Equatable {
    var participantCount: Int
    var votes: [String: [Vote: Int]]
    var notes: [String: String] = [:]
    var startedAt: Date

    init(participantCount: Int = 4) {
        self.participantCount = participantCount
        self.startedAt = Date()
        self.votes = [:]
        seedAllUp()
    }

    mutating func setParticipantCount(_ n: Int) {
        let clamped = max(2, min(12, n))
        guard clamped != participantCount else { return }
        participantCount = clamped
        seedAllUp()
    }

    private mutating func seedAllUp() {
        for cat in Category.all {
            votes[cat.id] = [.up: max(participantCount, 1), .sideways: 0, .down: 0]
        }
    }

    func count(in category: Category, zone: Vote) -> Int {
        votes[category.id]?[zone] ?? 0
    }

    mutating func move(in category: Category, from source: Vote, to destination: Vote) {
        guard source != destination,
              var zones = votes[category.id],
              (zones[source] ?? 0) > 0
        else { return }
        zones[source, default: 0] -= 1
        zones[destination, default: 0] += 1
        votes[category.id] = zones
    }

    // Primary "tap a zone" gesture: pull one token from the most logical source.
    // For sideways/down targets, prefer up first, then the other non-target zone.
    // For up targets, prefer sideways first, then down (a symmetric "undo").
    mutating func tapMove(in category: Category, to destination: Vote) {
        let preferred: [Vote] = switch destination {
        case .up: [.sideways, .down]
        case .sideways: [.up, .down]
        case .down: [.up, .sideways]
        }
        for source in preferred where count(in: category, zone: source) > 0 {
            move(in: category, from: source, to: destination)
            return
        }
    }

    // Score for one category: weighted average of vote values, rounded to 1-10.
    func score(for category: Category) -> Int {
        let weighted = Vote.allCases.map { ($0.score, count(in: category, zone: $0)) }
        let total = weighted.reduce(0) { $0 + $1.0 * $1.1 }
        let n = weighted.reduce(0) { $0 + $1.1 }
        return n == 0 ? 1 : Int((Double(total) / Double(n)).rounded())
    }

    var overallScore: Int {
        Category.all.reduce(0) { $0 + score(for: $1) }
    }

    var overallBand: RiskBand { ScoreColor.band(forOverall: overallScore) }

    func shareString() -> String {
        var out = "ORMA results\n"
        out += "Overall score: \(overallScore)  [\(overallBand.label)]\n\n"
        for cat in Category.all {
            out += "\(cat.title)\n"
            out += "Description: \(cat.description)\n"
            out += "Score: \(score(for: cat))\n"
            let note = (notes[cat.id] ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
            if !note.isEmpty {
                out += "Notes: \(note)\n"
            }
            out += "\n"
        }
        out += "Generated by Risk (group ORMA) at \(Date().formatted(.iso8601))."
        return out
    }
}
